### ISSUE TITLE
"Try" functionality broken on Chrome

### ISSUE THREAD

**Issue by oyeanuj** [microlinkhq/www#118]
Hi @Kikobeats, I went to the site to try the functionality and noticed that it was broken. I was clicking on different publisher icons and them black "Try" button to see how it might show up.

Here is a screenshot for the errors that I was seeing in the console - https://cl.ly/1h1f393E3K0c

This is on Chrome v69 on a Mac.

**Comment by Kikobeats** [comment]
Thanks for reporting, it should work fine right now, can you confirm? 🙂

**Comment by oyeanuj** [comment]
Yes, it works now!

Btw, it seems that clicking on the icon itself changes the preview and the snippet below, so the black "Try it" button in those cases seems redundant (or doesn't really do anything).

**Comment by Kikobeats** [comment]
You're right, the button is oriented in the cases you decide to provide an url to try it 🙂

**Comment by oyeanuj** [comment]
Not sure if this is related but when I try a custom link with the "try" button, the page crashes. You can try this link to replicate - http://scmp.com/week-asia/opinion/article/2112486/inconvenient-truths-murder-journalism-india
