### ISSUE TITLE
Cambio url bbc icon

### ISSUE THREAD

**Issue by pacosegovia** [microlinkhq/www#12]
Buenas! He intentado hacer un PR pero no tengo acceso. He visto que el link al apple-touch-icon de la bbc está roto, creo que el correcto es el siguiente:

https://static.bbci.co.uk/news/1.217.02127/apple-touch-icon.png

Un saludo.

**Comment by Kikobeats** [comment]
Gracias por el chivatazo 😄

Parece ser que el favicon está detrás de una CDN y cambia la URL en cada deploy, lo he hosteado en imgur y pa'lante

**Comment by pacosegovia** [comment]
YAY!

Paco Segovia

2017-11-03 11:11 GMT+01:00 Kiko Beats <notifications@github.com>:
