### ISSUE TITLE
API access

### ISSUE THREAD

**Issue by p6002** [microlinkhq/www#1615]
I found this documentation, there is information about sending a get request, but nowhere is the API address given. I would like to use the query as a trigger in n8n.io
https://microlink.io/docs/api/getting-started/overview

**Comment by Kikobeats** [comment]
Hello, check https://microlink.io/docs/api/basics/endpoint 🙂

**Comment by p6002** [comment]
Thanks, unfortunately I can't find the information I need there. 

It's a bit vaguely written that you only need http get to api, which is not true. The documentation also doesn't include examples of the query.

**Comment by Kikobeats** [comment]
Any software that can perform an HTTP GET can interact with the API endpoint:

```
curl https://api.microlink.io
```

That could be a UNIX command, a programming language, whatever.

What are you trying to achieve? What's your workflow?
