### ISSUE TITLE
Clickjacking Vulnerability

### ISSUE THREAD

**Issue by 0xhardik** [microlinkhq/www#1719]
Hello Security Team,

This is Suraj Kumar from india.I have discovered a security issue in your domain.Below details mentioned
here.

Vulnerability Name:
Clickjacking Vulnerability

Vulnerable URL:
https://microlink.io/
![micro](https://github.com/microlinkhq/open/assets/131232290/10b60354-3df9-41cb-925a-524a32977434)

Vulnerability Description:
Clickjacking is a type of web security vulnerability that allows an attacker to deceive a user into unknowingly clicking on something different from what they perceive. This vulnerability occurs when an attacker overlays an invisible or disguised element on top of a legitimate web page, tricking users into performing unintended actions.

Impact:
Clickjacking can have various negative consequences including:

Unauthorized actions: Attackers can trick users into unknowingly performing actions they did not intend to, such as clicking on hidden buttons or links that perform malicious actions.

Information disclosure: Clickjacking can be used to trick users into revealing sensitive information or performing actions that disclose confidential data.

Phishing attacks: Attackers can overlay a legitimate login form with a hidden malicious form, tricking users into entering their credentials, which can then be captured by the attacker.

Malware distribution: Clickjacking can be used to deceive users into clicking on buttons or links that initiate the download of malware or malicious files.

Mitigation:
Implement X-Frame-Options header: Set the X-Frame-Options header in HTTP responses to restrict the rendering of a webpage within a frame or an iframe. This can prevent the page from being embedded into other websites without permission.

Use Content Security Policy (CSP): Employ CSP directives to define the sources from which a browser should load content. Utilize the frame-ancestors directive to specify which domains are allowed to embed the page in a frame.

**Comment by Kikobeats** [comment]
Thanks for this! It should be fixed now 🙂

**Comment by Kikobeats** [comment]
I can give you credits adding your name, email and website into https://microlink.io/changelog

Please tell me  🙂

**Comment by 0xhardik** [comment]
Sorry team but I want bounty on my paypal…

do you have bug bounty program am I right ?

**Comment by Kikobeats** [comment]
Sorry but we don't have a bounty program

**Comment by Kikobeats** [comment]
before doing that: can you tell more about yourself?

How did you discover about Microlink? The only activity in your GitHub account is this issue, I have some curiosity about what's the history 🙂
