### ISSUE TITLE
Add search into docs

### ISSUE THREAD

**Issue by Kikobeats** [microlinkhq/www#413]
<img width="1552" alt="Screenshot 2020-04-28 at 14 27 12" src="https://user-images.githubusercontent.com/2096101/80487077-83d51d80-895c-11ea-9216-7bc9c5865238.png">

<img width="1552" alt="Screenshot 2020-04-28 at 14 27 36" src="https://user-images.githubusercontent.com/2096101/80487086-8899d180-895c-11ea-9756-3dc8e06e911e.png">

**Plugins**

- https://www.gatsbyjs.org/packages/gatsby-plugin-flexsearch/?=flex
- https://www.gatsbyjs.org/packages/gatsby-plugin-lunr/

**Related**

- https://assortment.io/posts/gatsby-site-search-lunr-js

**Comment by pixelastic** [comment]
Why not using [DocSearch](https://docsearch.algolia.com/)? It's entirely free and will crawl the documentation every 24h to update its index.

**Comment by Kikobeats** [comment]
@pixelastic oh true, definitely yes, just I need to find the way to fit at UI level, any suggestion? no idea how docsearch should be integrated

**Comment by pixelastic** [comment]
Basically, all you need is a search input in your design and `docsearch.js` handles the rest from a UI standpoint. It ships with default neutral styling, but you can override it in CSS if needed

**Comment by Kikobeats** [comment]
close in favour of #1099
