### ISSUE TITLE
Some stories from the storybook are down

### ISSUE THREAD

**Issue by tirabc** [microlinkhq/www#418]
## Bug Report

**Current Behavior**

Browsing stories at https://microlink.io/design are showing some errors in Input, CodeEditor and Notification sections.

**Expected behavior/code**

We should see components working in context.

**Possible Solution**

Wrap adjacent jsx in the stories

**Additional context/Screenshots**

![image](https://user-images.githubusercontent.com/573230/59664640-b6957d80-91b1-11e9-888b-c1006d8c3fb3.png)

**Comment by Kikobeats** [comment]
Thanks for reporting – this is happening because I added auto format code using prettier, but looks something is broken, let me take a look 🙂
