### ISSUE TITLE
direction does not fulfill its destiny 

### ISSUE THREAD

**Issue by pantchox** [microlinkhq/www#420]
Hi, 
when changing the direction i was more expecting changing the alignment of the text for languages such as Hebrew and Arabic, that is critical.

i think the direction property should be changed to "imagePosition/textPosition":"left/right"
and "direction" will apply for language. 

thank you!

**Comment by Kikobeats** [comment]
Not sure what you say, this repository is microlink.io website 🤔

Maybe are you talking about 
https://github.com/microlinkhq/sdk?

**Comment by pantchox** [comment]
yes you are right i will post there! sorry for mismatch.
