### ISSUE TITLE
How to setup(integrate) microlink API.

### ISSUE THREAD

**Issue by BoumBam** [microlinkhq/www#464]
Hello,

I have looked on your docs a long time about how to setup you API but I can't arrive It.
I tried that but not work:
`var url = $.get("microlink-api https://www.instagram.com/p/BeV6tOhFUor&userAgent=Googlebot");
 url.done(
    function(data) { 
        console.log(data);
  });`

Can't it used like GIphy API: `http://api.giphy.com/v1/gifs/search?q=laugh&api_key=my_key&limit=10`

Do you have some samples of using your  API ?
I'm using javascript.
thanks.

**Comment by Kikobeats** [comment]
this? https://microlink.io/docs/mql/getting-started/overview
